title: LinkSmart® - Free, Open Source IoT Platform
email: info@linksmart.eu
description: >
  LinkSmart® is an open source IoT platform offering services
  for device abstraction, data storage, and machine learning.

baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics: UA-35107405-3

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
  - nginx/
  - LICENSE

collections:
  tabs:
    output: false

sass:
    sass_dir: _sass

plugins:
  - jekyll-redirect-from
